version: "3.9" # optional since v1.27.0
services:
  db:
    image: mongo:5.0.6
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=surveys
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./db:/data/db/

  server:
    build: ./server
    depends_on:
      - "db"
    command: "python -u app.py"
    # command: "flask run"
    ports:
      - 5001:5001
    environment:
      - "TZ=America/Sao_Paulo"
      - "DB_URI=mongodb://db:27017/surveys"
      - "FLASK_ENV=development"
    volumes:
      - ./server:/opt/server

  # cron:
  #   build: ./server
  #   depends_on:
  #     - "db"
  #   command: "python -u cron.py"
  #   environment:
  #     - "TZ=America/Sao_Paulo"
  #     - "DB_URI=mongodb://db:27017/surveys"
  #   volumes:
  #     - ./cron.py:/app/cron.py

  client_1:
    image: nginx:1.21-alpine
    depends_on:
      - "server"
    ports:
      - 6001:80
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./client:/usr/share/nginx/html

  client_2:
    image: nginx:1.21-alpine
    depends_on:
      - "server"
    ports:
      - 6002:80
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./client:/usr/share/nginx/html

  client_3:
    image: nginx:1.21-alpine
    depends_on:
      - "server"
    ports:
      - 6003:80
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./client:/usr/share/nginx/html

  # client_old:
  #   build: ./client
  #   depends_on:
  #     - "server"
  #   command: "sleep infinity"
  #   environment:
  #     - "TZ=America/Sao_Paulo"
  #   volumes:
  #     - ./client:/opt/client
